version: '3.8'

services:
  #postgres database service
  db:
    image: postgres:13
    container_name: railsathi_db
    environment:
      POSTGRES_DB: rail_sathi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # FastAPI application service
  app:
    build: .
    container_name: railsathi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app # this one is the bonous feature which is used for code hot-reloading in development mode which provides development convenience
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rail_sathi_db
      - MAIL_USERNAME=test@example.com
      - MAIL_PASSWORD=test_password
      - MAIL_FROM=test@example.com
    command: ["./wait-for-it.sh", "db", "5432", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data: